#
#  © 2022 PERLUR Group
#  SPDX-License-Identifier: GPL-3.0-only
#

name: GitHub Pages

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  deploy:
    name: Deploy mdBook
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
      - name: Read .env
        id: mdbook-version
        run: |
          cd src/frontend/docs/
          . ./.env
          echo "::set-output name=MDBOOK_VERSION::${MDBOOK_VERSION}"
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '${{ steps.mdbook-version.outputs.MDBOOK_VERSION }}'
      - uses: actions-rs/install@v0.1
        with:
          crate: mdbook-linkcheck
          version: latest
          use-tool-cache: true
      - run: |
          cd src/frontend/docs
          mdbook build
      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_dir: docs/
          cname: NuPeerStack.perlur.cloud
